# Generated by Django 5.2 on 2025-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Полное имя автора')),
                ('bio', models.TextField(verbose_name='Краткая биография автора')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('authors', models.ManyToManyField(related_name='books', to='products.author', verbose_name='Автор(ы)')),
            ],
        ),
    ]
