# Generated by Django 5.2 on 2025-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_book_options_alter_review_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='carts',
            field=models.ManyToManyField(related_name='books', to='products.cart'),
        ),
    ]
