# Generated by Django 5.2 on 2025-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_cart_book_book_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='carts',
        ),
        migrations.AddField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(related_name='carts', to='products.book'),
        ),
    ]
