# Generated by Django 5.2 on 2025-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_book_carts_cart_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(null=True, related_name='carts', to='products.book'),
        ),
    ]
